### ISSUE TITLE
Template error

### ISSUE THREAD

**Issue by markcs** [bremor/bureau_of_meteorology#106]
Using version 1.1.1 via HACS
Version Home Assistant 2022.3.5

I see this error in the logs which indicates this will not work properly now?

`2022-03-15 21:09:01 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'round' got invalid input 'unknown' when rendering template '{% if states('sensor.mylocation_temp_min_0') == 'unknown' %} {% set min = states('sensor.bom_today_min') %} {% else %} {% set min = states('sensor.mylocation_temp_min_0') %} {% endif %} {% if states('sensor.mylocation_temp_max_0') == 'unknown' %} {% set max = states('sensor.bom_today_max') %} {% else %} {% set max = states('sensor.mylocation_temp_max_0') %} {% endif %} {{ max|round(0)}}°/{{ min|round(0)}}°/{{states('sensormylocation_rain_chance_0')|round(0)}}%' but no default was specified. Currently 'round' will return 'unknown', however this template will fail to render in Home Assistant core 2022.1
`

**Comment by DavidFW1960** [comment]
It looks like you are talking about my templates in the BOM/Generic Weather card - not this component right? All my templates have been updated for the template changes in home assistant. Please close this issue here as it has nothing to do with this component and open an issue in the repo for the card if you can't fix it.
