### ISSUE TITLE
hourly entity displaying 'snowy' for frost warning

### ISSUE THREAD

**Issue by lichenophile** [bremor/bureau_of_meteorology#142]
![image](https://user-images.githubusercontent.com/67679349/177326399-f662f9af-d1c8-4f45-9e3f-ca687cc48408.png)
Example of attribute data:
```
- datetime: '2022-07-05T18:00:00Z'
  temperature: 4
  condition: snowy
  precipitation: 0
  precipitation_probability: 5
  wind_bearing: NNE
  wind_speed: 1.67
```

The hourly integration has 'snowy' reported for the hours of 4-9am. BoM website disagrees. Snow is also _very_ improbable for my area.

There is currently a [minor frost warning](http://www.bom.gov.au/vic/warnings/frost.shtml) for the area that covers that time period. I can only assume that this is erroneously being reported as snow by either the integration, or perhaps the api this integration uses?

![image](https://user-images.githubusercontent.com/67679349/177328250-f985760f-039f-4d61-9284-0e6262cbcc2a.png)

**Comment by Makin-Things** [comment]
Unfortunately this is a problem caused by home assistant. For the weather.xxxx entities they restrict what values can be stored in the condition attribute to what is on this list.
[https://www.home-assistant.io/integrations/weather/](url)
So integrations have to do some sort of mapping from the real condition (currently for your location the condition being reported by the BoM is ``frost``. I suspect you are not far from me as I see the same thing). The integration currently maps that to ``snowy`` and I can't see anything better to map it to.
There logic is that there needs to be an mdi:icon available for any condition they are going to include, which results in wrong data due to the translation required.
Maybe raise an issue against the weather integration [https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+weather%22](url) to get them to add more conditions. There is an mdi icon snowflake-melt which is probably the best for frost.
