### ISSUE TITLE
No minimum temp at night

### ISSUE THREAD

**Issue by oneseventhree** [bremor/bureau_of_meteorology#143]
Hi,

I noticed that at night the sensor goes to "unknown":
<img width="490" alt="Screen Shot 2022-07-06 at 5 59 13 pm" src="https://user-images.githubusercontent.com/15043282/177500666-d2f88b87-47e8-4143-95aa-1881d95867bd.png">

On the BOM app it shows that there is an overnight min of 6:
![IMG_9642](https://user-images.githubusercontent.com/15043282/177500725-36760d5c-bfa1-4c98-8b25-fe06497dcef7.jpg)

Is there a way to display the overnight min temp? Is there another sensor for it?

Thanks for a great integration!

**Comment by Makin-Things** [comment]
Have a look at some recently added sensors that duplicate the BoM's behavior.
![image](https://user-images.githubusercontent.com/91187456/177502829-8abd84af-ffb6-47fc-b555-1aa6d019a89a.png)
They basically provide the next and following min or max in chronological order. The names are a bit ugly because to they are a flattened version of what the bom have in their json data.

**Comment by Makin-Things** [comment]
Also we added those as slot values in David's card and also the new platinum-weather-card.

**Comment by oneseventhree** [comment]
> Have a look at some recently added sensors that duplicate the BoM's behavior. ![image](https://user-images.githubusercontent.com/91187456/177502829-8abd84af-ffb6-47fc-b555-1aa6d019a89a.png) They basically provide the next and following min or max in chronological order. The names are a bit ugly because to they are a flattened version of what the bom have in their json data.

Ah yes. This worked - shame about the naming. Makes it a bit confusing.
