### ISSUE TITLE
Getting coordinates as location name

### ISSUE THREAD

**Issue by bremor** [bremor/bureau_of_meteorology#3]
@dubsix getting coordinates as my location name in sensors and location name in integration was 50km off, browsing API directly all works ok with the coordinates I use

![image](https://user-images.githubusercontent.com/34525505/97512096-c8f60d00-19dc-11eb-9e2d-c1d6fd730b8c.png)

**Comment by bremor** [comment]
I can't replicate your error, but I uncovered a seperate bug.. please update to v0.5 and remove/re-add the integration and let me know how it goes.

**Comment by warwickbuilds** [comment]
Thanks will do shortly.

It picked up my long/lat from HA config, but resolved to Hindmarsh Island with is 50km away from Adelaide, so I entered in manually from google which returns both the - and non- coords

**Comment by warwickbuilds** [comment]
looks to be an issue with resolving from a long/lat rather than name.

example for West Beach - 
google co-ordinates gives me -34.9453° S, 138.5038° E = geohash r1f3pw
https://weather.bom.gov.au/location/r1f3pw
bom search for west beach gives me geohash r1f3py7

If I reverse the geohash and utilise those long/lat the correct name is used in the integration.

Maybe note to reverse geohash in instructions if this happens.

Thanks again for getting this integration up and running so quick!

**Comment by bremor** [comment]
Those coordinates are just off the coast, in the bay, maybe that is why?
https://www.google.com/maps/place/34%C2%B056'41.2%22S+138%C2%B029'56.9%22E/@-34.9479521,138.4956495,14.75z/data=!4m5!3m4!1s0x0:0x0!8m2!3d-34.9447632!4d138.4991455

**Comment by bremor** [comment]
So the coordinates are only granular down to 4 decimal places, so they snap to the gridline at 4 decimal places which happens to put your location in the water, you must live very close to the water :)
If you move your location a couple of hundred meters inland it should work.

**Comment by warwickbuilds** [comment]
so it is, all good now, thanks.
